# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - WebAppMaximeJacquat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://acr300621210.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ef13761fca2c49f49edee00b64da0a97 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9c989142aefb4cc2b872e23ad2912baa }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ef13761fca2c49f49edee00b64da0a97 }}/jam-todo-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'WebAppMaximeJacquat'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0bed3e89d967445283b2358036a2a73a }}
        images: 'acr300621210.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ef13761fca2c49f49edee00b64da0a97 }}/jam-todo-app:${{ github.sha }}'